create table if not exists public.turmas_config (
    id bigint generated by default as identity primary key,
    turma text not null unique,
    coordenador_sala text,
    updated_at timestamptz default now()
);

create index if not exists turmas_config_idx_turma
on public.turmas_config (turma);

create or replace function public.set_updated_at_turmas_config()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_set_updated_at_turmas_config on public.turmas_config;

create trigger trg_set_updated_at_turmas_config
before update on public.turmas_config
for each row
execute function public.set_updated_at_turmas_config();

alter table public.turmas_config enable row level security;

drop policy if exists "turmas_config_select_authenticated" on public.turmas_config;
create policy "turmas_config_select_authenticated"
on public.turmas_config
for select
to authenticated
using (true);

drop policy if exists "turmas_config_insert_authenticated" on public.turmas_config;
create policy "turmas_config_insert_authenticated"
on public.turmas_config
for insert
to authenticated
with check (true);

drop policy if exists "turmas_config_update_authenticated" on public.turmas_config;
create policy "turmas_config_update_authenticated"
on public.turmas_config
for update
to authenticated
using (true)
with check (true);

drop policy if exists "turmas_config_delete_authenticated" on public.turmas_config;
create policy "turmas_config_delete_authenticated"
on public.turmas_config
for delete
to authenticated
using (true);
