create table if not exists public.relatorios_estudantes (
    id bigint generated by default as identity primary key,
    turma text not null,
    ra text not null,
    aluno text not null,
    data_inicio date not null,
    data_fim date not null,
    professor_autor text,
    professor_responsavel_sala text,
    coordenador_sala text,
    componente_curricular text,
    situacao_geral text default 'Em acompanhamento',
    frequencia_percentual numeric(5,2) default 100,
    desenvolvimento_academico text,
    observacoes_comportamentais text,
    estrategias_adotadas text,
    pontos_atencao text,
    pontos_atencao_automaticos jsonb default '[]'::jsonb,
    indicacao_grave_professor boolean default false,
    descricao_ponto_grave text,
    ultima_edicao_por text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create index if not exists relatorios_estudantes_idx_turma
on public.relatorios_estudantes (turma);

create index if not exists relatorios_estudantes_idx_ra
on public.relatorios_estudantes (ra);

create index if not exists relatorios_estudantes_idx_periodo
on public.relatorios_estudantes (data_inicio, data_fim);

create or replace function public.set_updated_at_relatorios_estudantes()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_set_updated_at_relatorios_estudantes on public.relatorios_estudantes;

create trigger trg_set_updated_at_relatorios_estudantes
before update on public.relatorios_estudantes
for each row
execute function public.set_updated_at_relatorios_estudantes();

alter table public.relatorios_estudantes enable row level security;

drop policy if exists "relatorios_estudantes_select_authenticated" on public.relatorios_estudantes;
create policy "relatorios_estudantes_select_authenticated"
on public.relatorios_estudantes
for select
to authenticated
using (true);

drop policy if exists "relatorios_estudantes_insert_authenticated" on public.relatorios_estudantes;
create policy "relatorios_estudantes_insert_authenticated"
on public.relatorios_estudantes
for insert
to authenticated
with check (true);

drop policy if exists "relatorios_estudantes_update_authenticated" on public.relatorios_estudantes;
create policy "relatorios_estudantes_update_authenticated"
on public.relatorios_estudantes
for update
to authenticated
using (true)
with check (true);

drop policy if exists "relatorios_estudantes_delete_authenticated" on public.relatorios_estudantes;
create policy "relatorios_estudantes_delete_authenticated"
on public.relatorios_estudantes
for delete
to authenticated
using (true);
